# config.yaml
backtesting:
  start_date: "2018-01-01"
  end_date: "2024-01-01"
  initial_capital: 100000

data:
  raw_data_dir: "data"
  processed_data_dir: "processed_data"

index:
  symbol: "^GSPC"

output:
  dir: "backtest_results"
  log_file: "backtest.log"

strategy:
  momentum_window: 90
  ma_window: 100
  long_trend_window: 200
  atr_window: 14
  max_gap: 0.15
  rebalance_threshold: 0.1

transaction_costs:
  commission_rate: 0.001
  slippage_rate: 0.0005
