# Data Configuration
data:
  source: yahoo # or 'csv'
  directory: data/raw
  start_date: "2010-01-01"
  end_date: "2021-12-31"
  symbols:
    - AAPL
    - GOOGL
    - MSFT
  index_symbol: "^GSPC" # S&P 500

# Strategy Parameters
strategy:
  name: momentum
  lookback_period: 90
  trend_ma_window: 100

# Portfolio Parameters
portfolio:
  initial_capital: 1000000
  risk_per_trade: 0.001 # 0.1% risk per trade

# Execution Parameters
execution:
  commission_rate: 0.001 # 0.1% commission per trade

# Backtest Settings
backtest:
  rebalance_frequency: 10 # Rebalance every 10 trading days
